### ISSUE TITLE
[Project_FIFA_MoneyBall] Spica

### ISSUE THREAD

**Issue by sumampouw** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#11]
I used Plotly to visualize some of the questions, so some graphs will not be shown here and need to be run in your machine. Thanks, and looking forward to your feedback.

https://github.com/sumampouw/Project_FIFA_MoneyBall

**Comment by Unaiat** [comment]
Hi Spica 🙋‍♂️ Here I send you some feedback of the first project. 

First of all, I want to congratulate you for the project. You did a very good job. 

The readme is very clear and gives the necessary information to understand what you did in the project. 

Regarding the ipynb file, you named it as solutions, as we do with the labs. Just FYI, you can choose the name you prefer, it is not mandatory to do so. 

When reading the csv, you do not need to put the whole path to the file, just the relative path is enough. 

The relative path starts in the current working directory, that is, the directory where the notebook is saved. The relative path would be the following:

```python
data = pd.read_csv('./Data/fifa21_male2.csv')
```
Please note that the ipynb file and the folder where the csv file is need to be in the same level (inside the same folder). 

This is important, as otherwise if someone else downloads your folder the code will not work, and they will need to change the path. 

The notebook is very well structured and you explain the main decisions you take. 

It is impressive that you used many new libraries and tools that were not covered in class. This is great, and we can see that you understand how they work. Please always remember that it is very important to understand what all the algorithms and metrics do. We always try to get the best result possible, but we cannot lose focus on understanding each of the steps and always think how to justify each decision. 

Your question were interesting and you answer them clearly using visualizations. This is very important as a data analyst, so it is very good that you are already doing it 😀

Please, let us know if you have any question. 

Keep up the good work!!! 🚀
