### ISSUE TITLE
[Silvia] FIFA Project

### ISSUE THREAD

**Issue by silviagonzalez98** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#13]
https://github.com/silviagonzalez98/Project-FIFA-Python.git

**Comment by fromeropablo** [comment]
# Moneyball Project

Hi Silvia! Let's go with corrections of your first project as a Data Analyst! That's a big step after all the labs done and I do hope that you have enjoyed the process during the week to complete your project! 

Yu have done a good work here to be your first project, but you didn't propose any question further than your Machine Learning model and it was an important goal for the project aswell. 

## 1. ReadME and Miscellanous

Your ReadME works fine and gives a good shot of what have you done in your project. 

However, you can improve it to engage more people when they'll see your repository. And you will think, how?

- At first sight, the structured is really good but it seems a bit short. That's something similar to your presentation letter to check your work, this file it's the very first thing readers will watch when they click in your repo!

- It's important to create a good storytelling. Your projects won't be just your code, idea and data, but also the way that you present it to the world! For example, you can add some images as I'm gonna show you:
```markdown
![Zones of the court](./images/polygon_court.png)
```
The first part of the line, the one inside square brackets, represents the words that should appear in case that the image doesn't show properly. The second part is the image itself. To do in the same way you should create a folder in your repo (from Visual Studio) called `images` and save the images you wanna show there.  

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```
Similar to what I told you before, the first part is the title or what every user will see in your repo and the second part is the link to the documentation of that module. It will appear in Github in blue words as a hyperlink. I saw that you did it in your section #4 adding the link of the sources of your data, that's great!

-Finally, it seems that you have done successfully your .gitignore file hiding your csv file on it, great work!

## 2. What about your code?

As well as your **ReadME**, your jupyter notebook is clearly well organized and your explanations about every step that you do are good. Remember that about that last point, you can always create a *markdown* cell to give your explanations more clearly.

Great that you have imported all your libraries and your data at the beginning of your notebook! It's a very important step to do in the same way from now, forever. It helps other people who take a look at your code to check your libraries and its tools as well as your data. 

### 2.1 Questions

Where are your questions??? It had been great if you would ask yourself about a few problems to solve and answer them using data. If you have any free time in the future, I assume that's why you don't have any, I would tell you to propose some of them with different levels of complexity and try to solve them. 

### 2.2 Exploratory analysis

Your work here is good! You have use a lot of `Pandas` methods, `for` loops, `list comprehension`... Also, you used a few functions, which are always useful to simplify our code. 

Just some tips to improve:

- Great work explaining at the beginning why you are dropping specific columns! 

- When you fill the missing values with the mean, which is a good technique, you can optimize your code creating a function which takes the name of the column as a parameter. Then, you can use `apply` method to do it in one step saving you a lot of time typing the same line of code. Also, you can create a list with the name of the columns you want to fill and iterate by them using a `for` loop. 

- I missed some more functions or solving cleaning tasks, for example, changing the value of weight from lbs to kg. It's easy creating a function for it. In your final DataFrame, to check correlation, you still has 60 variables remaining, it would be better if you clean them a little bit more or decide to drop some of them because their significant is similar to other variables. 

### 2.3 Processing analysis

Once you cleaned all your data and you understood the variables you have to work with, it's time to do the processing analysis, which is the main step of a Machine Learning model. 

- As you still have a lot of numerical variables, it's better to not display the value of correlation between variables in your *correlation* matrix. It would be easier to understand it just with the colours of each block and the legend at the right side. 

- Great work removing outliers with the function that we saw in class. You just forgot to check for the distribution of your variables. It's always important to check your variables, also your target one, to normalize some of them if they don't have a normal distribution. It will improve your R-Square, presumably. 

- Cool that you encoded your categorical data but take in count that your model has now more than 60 variables. They will add so much noise to your model and won't allow to detect which features are explaining the bigger part of it. Having a small number of variables is as important as having a good R-Square.
