### ISSUE TITLE
Yuri_Awano_Project 1

### ISSUE THREAD

**Issue by yuawano** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#17]
https://github.com/yuawano/P1_MoneyBall_FIFA/tree/main/Data

**Comment by fromeropablo** [comment]
# Moneyball Project

Hi Yuri! Let's go with corrections of your first project as a Data Analyst! That's a big step after all the labs done and I do hope that you have enjoyed the process during the week to complete your project! 

Yu have done a really good work here and you should be very happy for that. Keep working and showing tones of effort in your work, congrats!

## 1. ReadME and Miscellanous

Your ReadME works fine, it's really clean, well-structured and gives a good shot of what have you done in your project. 

However, you can improve it to engage more people when they'll see your repository. And you will think, how?

- It's important to create a good storytelling. Your projects won't be just your code, idea and data, but also the way that you present it to the world! For example, you can add some images as I'm gonna show you:
```markdown
![Zones of the court](./images/polygon_court.png)
```
The first part of the line, the one inside square brackets, represents the words that should appear in case that the image doesn't show properly. The second part is the image itself. To do in the same way you should create a folder in your repo (from Visual Studio) called `images` and save the images you wanna show there.  

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```
Similar to what I told you before, the first part is the title or what every user will see in your repo and the second part is the link to the documentation of that module. It will appear in Github in blue words as a hyperlink. 

- About the structure of your repo, take in count that you have five different jupyter notebooks to show your work. It isn't the cleanest way to have it, it's better to have one and work just on that one, doing commits every time to save your progress. If you have any doubt about it, don't hesitate to contact me to help you with it. 

- The **.gitignore** file that you created had the purpose to hide the csv file that you worked with. It's as easy as open Visual Studio or PyCharm and go to the .gitignore file and type there the name of the file that you want to hide in Github. If you have any doubt about it, once again, don't hesitate to contact me. 
- Finally, great that you created a new folder saving your data files there, good work!

## 2. What about your code?

Your final jupyter notebook is clearly well organized and your explanations about every step that you do are good. Remember that about that last point, you can always create a *markdown* cell to give your explanations more clearly.

Great that you have imported all your libraries and your data at the beginning of your notebook! It's a very important step to do in the same way from now, forever. It helps other people who take a look to your code to check your libraries and its tools as well as your data. 

### 2.1 Exploratory analysis

Your work here is brilliant, congrats for it! It's cool that you have used a lot of concepts learned in class such as `list comprehension`, `apply & lambdas`, `regex`, **Pandas** methods and functions.

Just some tips to improve: 

- It seems that you have filled missing values from different columns with the *composure* mean. If you decide to fill null values with the mean, it has to be the mean of each variable. Also, instead of filling every column one by one, you can create a function with the name of the column as a parameter or create a list with the columns you want to fill values and use a for loop to iterate by them.

- Be careful showing all the unique values of every column. It adds a lot of noise to your jupyter notebook and readers (and also you) will have to scroll too much time reading every unique value of your data. 

- Great work, as I said, using `apply` and `lambdas` methods along to `regex` in following cells. 

- In fact, in that *regex* cell, you can create a function or a `for` loop similar to what I said to you in the first bulletpoint. 

- Overall, your cleaning work is perfect, congrats!

### 2.2 Questions

Great election of questions to answer, congrats! They have a good level of complexity, could be useful for further approaches and you have used visualization libraries to show your answers in a prettier way!

Your workflow here is perfect, very good presentation of your data and explanation of the results and the process, congrats!

- Just a quick tip. You can create a function for the correlation matrix code lines. You establish as a parameter the correlation of each subset of data with the name of *correlation_matrix* for example. It will save you some time and your code will be optimized. 

### 2.3 Processing analysis

Once you cleaned all your data and you understood the variables you have to work with, it's time to do the processing analysis, which is the main step of a Machine Learning model. 

- Great work here checking for distributions and outliers of your selected variables! It's a very useful exercise to do every time we can run a Linear Regression. 

- You finished your model with just 27 columns, counting that 12 of them comes from a categorical one, that's a good number of features knowing that we started with more than 100. 

Also, you have showed your results in a DataFrame to help readers understand them, that's a good point! 

I have nothing else to say in your project, just remember to import all your libraries and modules at the first cell of your jupyter notebook. Great work overall, keep going in the same way!
