### ISSUE TITLE
https://github.com/SophieHubert/P1_MoneyBall_FIFA.git

### ISSUE THREAD

**Issue by SophieHubert** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#18]

**Comment by AnaAGG** [comment]
# ⚽️ Money Ball FIFA project ⚽️

Hi Sophie, here I am with the first project review. 

## Readme

Suuuper you have defined three cleary questions in your project 👏🏽

Just as a detail, this dataset could be a bit complex because it have a lot of columns with a lot of information about concepts that some people may find confusing or simply not know. One thing that you could do is add a little description about each of the concepts. 

What did I miss in your readme?

- A good practice in the readme is to put the link to the website where the data can be downloaded, in this case kaggle.

- I see that you have asked all three questions but in no case do I see the overall objective of the project. This is very important to know what this work is about. 

- One importatn thing I missed in your readme are the libraries that you have used in the project. You can put them on a list and if you add link to the official website it would be perfect. For example: 
  - pandas
  - numpy
  - matplotlib
  - ...
  
        [pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)

        If you use this structure you create a link like the ones we create for you when we send you documentation. 

        Example 👇🏽👇🏽

    [Here](https://www.markdownguide.org/cheat-sheet/) a markdown cheat-sheet in case it help you in the future
 



## Repo structure

The structure is perfect, you have a readme and main jupyter and the gitignore, and the most important! No temporary files such as `vscode` or `DS_Store` have been left out of the gitignore. 

## Code syntax

- Suuper using SQL in this project Sophie 🔝! 

- What happend with the number of rows in your dataset
  
- Regarding the fill na, two important things here:
  
  - You don't have nan in your data, so... why you use the `fillna` method?
  
  - You replace the `nan` values with 0, but... why? Sometimes the best option is replace with the mean or with the mode. In addition, consider that there will be columns that are categorical and that you are replacing numerical values in categorical columns. Therefore, the replacement of null values should be done after a thorough exploration of each column and evaluating which is the best option to replace our data. 

- Suuper creating the `num_cleaning` function Sophie 🔝👏🏽. One of the main objectives of a function is avoid repeat many times the same lines of code. In your case, you function is perfect. To be picky, you apply the function into three different columns, and thus you repeated the code 3 times. Imagine that you want to repeat the code 20 times.. it could very painful. One option to solve this problem is use a `for` loop, here an example:
    ```python
    # first, we create a list with the name of the target columns 

    lst = ["wage", "value", "release_clause"]

    # then iterate over the list and apply your function

    for column in lst:
        data[column] =pd.to_numeric(data[column].apply(num_cleaning))
        # In this way you have the same code but only in three lines 
    ```
- When you drop columns, you did it in two different lines of code, try to unify and do it all at once
    ```python
    # Instead of 
    data.drop(['player_photo', 'club_logo', 'flag_photo', 'loan_date_end' , 'w/f' , 'sm'], axis=1, inplace=True)


    data.drop(['ls','st','rs','lw','lf','cf','rf','rw','lam','cam','ram','lm','lcm','cm','rcm','rm','lwb','ldm','cdm','rdm','rwb','lb','lcb','cb','rcb','rb','gk'], axis=1, inplace=True)

    # you should do: 
    data.drop(['ls','st','rs','lw','lf','cf','rf','rw','lam','cam','ram','lm','lcm','cm','rcm','rm','lwb','ldm','cdm','rdm','rwb','lb','lcb','cb','rcb','rb','gk', 'player_photo', 'club_logo', 'flag_photo', 'loan_date_end' , 'w/f' , 'sm'], axis=1, inplace=True)
    ```
- You calculate the variable correlation before fit the model, why? Remember, we used the correlation to check the autocorrelation between variables with the objective to remove variables that they are basically telling us the same thing. So... when we have variables highly correlated we should remove one of them

- The same goes for when you make displots, we use them to evaluate if our variables follows a normal distribution. In case the variables do not follow a normal distribution, we need to transform them using the normalization. 

- Only as a detail, as a convention the imports in python ususally go at the beginning of the jupyter. 
  
- The errors you had in the plots are because the specified columns is not in the dataframe. 

- ⚠️ So... as summary (the steps that you should do in a machine learning model) when we create a machine learning model: ⚠️
  - Load the data
  - Explore the data in our dataset
      - Check missing values
      - Correlation matrix among variables
      - Check numeric and categorical variables
      - Check the outliers and remove them
      - Normalize (numerical variables) and One Hot/Label Encoding(categorical)
  - Perform different model and check what is the best, for this we can use:
    - R2
    - mse
    - rmse
    - mae
  
## TODOs

- Some visualization for example with the tables that you get with the most valued players. Your tables and results show clearly your hypothesis, but visualization could be more friendly for a person (or customer) who is not familiar with python. 
Remember, you have a lot of libraries in python that you could use with this objetive, my favorite... [plotly](https://plotly.com/python/plotly-express/)

- Reorganise the workflow of the prediction model, remember, order is important.

- Work in the readme. Is the first thing people will see of your repository and where you will explain how you have worked and what you are capable of doing. Go for it! 

All in all Sophie, you have done an amazing job on your first project. In this project you have reinforced the knowledge acquired so far in the bootcamp. You have explored the data, familiarised yourself with it, cleaned it and created a machine learning model with very good results, and you have added more data, amazing🚀🚀🔥🔥!!!!



![image](https://user-images.githubusercontent.com/75084991/126365369-0948ddc0-7b4e-4609-8db6-269450f36ecf.png)
