### ISSUE TITLE
P1_FIFA_MoneyBall_Rita

### ISSUE THREAD

**Issue by ritasilv** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#19]
[https://github.com/ritasilv/P1_FIFA_MoneyBall.git](url)

**Comment by ritasilv** [comment]
https://github.com/ritasilv/P1_FIFA_MoneyBall.git

**Comment by Unaiat** [comment]
Hi Rita 🙋‍♂️ Here I send you some feedback of the first project. 

First of all, I want to congratulate you because you did a very good project. It is very well structured and is easy to follow. 

I will start with some recommendation and finish with an overall summary:

When reading the csv, you do not need to put the whole path to the file, just the relative path is enough. 

The relative path starts in the current working directory, that is, the directory where the notebook is saved. The relative path would be the following:

```python
data = pd.read_csv('./Data/fifa21_male2.csv')
```
Please note that the ipynb file and the folder where the csv file is need to be in the same level (inside the same folder). 

This is important, as otherwise if someone else downloads your folder the code will not work, and they will need to change the path. 

Regarding the doubt that you have to see all the data types of all the columns together, you can use this code:

```Python
data.info(verbose=True)
```

However, your solution of using indexes also to check amount of null values, for example, is good too. 

In general you understood all the code you found on the Internet, there was only one where you didn't understand some lines in the `def value_to_float(x)` function. If there is something you do not understand, please let us know and we will check it with you. It is common practice to look for solutions online, but it is essential to always understand the logic behind every code we use. Your approach is perfect. 

Just one suggestion, it is a convention to use `elif` instead of repeating `if` in the conditional statements with more than one condition. Here I send you some documentation about it:

[elif statements documentation](https://docs.python.org/3/tutorial/controlflow.html) https://docs.python.org/3/tutorial/controlflow.html

When creating the dataframe with the variables to use for the model, it would be nice to add the reasoning behind the decision. It could be subjective, based on previous knowledge of the topic, or based on research you did regarding the topic. I think that you said you got it from a link that was shared by a classmate, which is perfectly fine. This is more a recommendation also for future cases. 

Finally, please also import all the libraries at the beginning 😀. You basically made it, except the `from scipy.special import inv_boxcox` and `import math` at the end of the notebook. Again, this is a convention and not a mistake. 

The readme is very good and provides all the necessary information. You proposed very interesting questions and answer them using great graphs. The use of visualizations to explain the results is very important, and you did a very good job in this regard. 

You demonstrated that you understand the fundamentals of Linear Regression and you are able to apply the model. 

Please, let us know if you have any question. 

Keep up the good work!!! 🚀
