### ISSUE TITLE
Submit by Karolin Diede

### ISSUE THREAD

**Issue by KaroD123** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#2]
https://github.com/KaroD123/Project1_MoneyBall_FIFA

**Comment by fromeropablo** [comment]
# Moneyball Project

Hi Karo! Let's go with corrections of your first project as a Data Analyst! That's a big step after all the labs done and I do hope that you have enjoyed the process during the week to complete your project! 

Yu have done a really good work here and you should be very happy for that. Keep working and showing tones of effort in your work, congrats!

## 1. ReadME and Miscellanous

Your ReadME works fine, it's really clean, well-structured and gives a good shot of what have you done in your project. 

However, you can improve it to engage more people when they'll see your repository. And you will think, how?

- It's important to create a good storytelling. Your projects won't be just your code, idea and data, but also the way that you present it to the world! For example, you can add some images as I'm gonna show you:
```markdown
![Zones of the court](./images/polygon_court.png)
```
The first part of the line, the one inside square brackets, represents the words that should appear in case that the image doesn't show properly. The second part is the image itself. To do in the same way you should create a folder in your repo (from Visual Studio) called `images` and save the images you wanna show there.  

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```
Similar to what I told you before, the first part is the title or what every user will see in your repo and the second part is the link to the documentation of that module. It will appear in Github in blue words as a hyperlink. 

- The **.gitignore** file that you created had the purpose to hide the csv file that you worked with. It's as easy as open Visual Studio or PyCharm and go to the .gitignore file and type there the name of the file that you want to hide in Github. If you have any doubt about it, don't hesitate to contact me. 


## 2. What about your code?

As well as your **ReadME**, your jupyter notebook is clearly well organized and your explanations about every step that you do are good. Remember that about that last point, you can always create a *markdown* cell to give your explanations more clearly.

Great that you have imported all your libraries and your data at the beginning of your notebook! It's a very important step to do in the same way from now, forever. It helps other people who take a look to your code to check your libraries and its tools as well as your data. 

### 2.1 Questions

Your questions are good, but it's absolutely mandatory to do all the cleanliness of your data before answer it!! 

If you just check for duplicates, you might lose some important insights because you didn't do a deeper cleanliness before it, so your questions could be incorrect or not accurate enough. 

Moreover, in future occasions you can give a spin to your questions and do some more complex ones. You are able to do it after cleaning your data without any problem!!

### 2.2 Exploratory analysis

Your work here is really great, congrats for it! It's cool that you have used a lot of concepts learned in class such as `list comprehension`, `apply & lambdas`, `regex` and **Pandas** commands. 

Just some tips to improve: 

- In my opinion, I wouldn't remove the **Name** column because it can help you to understand your data and that's the key of every project you do. 

- Be careful to print or display your dataset quite often. It adds so much noise to your jupyter and it's difficult for readers to follow your workflow. Get used to return just a few rows of your data to analyse every change that you have done. The `.head()` method helps a lot. 

- As I said, great work using `regex` but in this case that you repeat the same line of code, just changing the column where you apply the pattern, you might create a list with the name of the columns as strings and do a `for` loop to iterate by them or create a function where the parameter will be the name of the column to improve your code and save some lines and time.

### 2.3 Processing analysis

Once you cleaned all your data and you understood the variables you have to work with, it's time to do the processing analysis, which is the main step of a Machine Learning model. As above, just a few things to improve:

- As you still have a lot of numerical variables, it's better to not display the value of correlation between variables in your *correlation* matrix. It would be easier to understand it just with the colours of each block and the legend at the right side. 

- Don't confuse normalization with outliers. At the beginning you create all your boxplots to check outliers and then you normalize your variables without checking for the distribution of every variable. They are different and it's not always cool to normalize all your data because some variables might have a normal distribution itself. If you have any doubt about it, contact me!

Finally, great work with your OLS summary and your linear regression, you have done a great great work overall!
