### ISSUE TITLE
ZigaKolar_Moneyball-FIFA

### ISSUE THREAD

**Issue by Ziga-K** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#20]
https://github.com/Terminal-zkolar/Project1_Moneyball-FIFA-ZigaKolar-

**Comment by fromeropablo** [comment]
# Moneyball Project

Hi Ziga! Let's go with corrections of your first project as a Data Analyst! That's a big step after all the labs done and I do hope that you have enjoyed the process during the week to complete your project! 

Yu have done a good work here and you should be happy for that. Keep working and showing tones of effort in your work!

## 1. ReadME and Miscellanous

Your ReadME works fine and gives a good shot of what have you done in your project. 

However, you can improve it to engage more people when they'll see your repository. And you will think, how?

- At first sight, the structured is really good but it seems a bit short. That's something similar to your presentation letter to check your work, this file it's the very first thing readers will watch when they click in your repo!

- It's important to create a good storytelling. Your projects won't be just your code, idea and data, but also the way that you present it to the world! For example, you can add some images as I'm gonna show you:
```markdown
![Zones of the court](./images/polygon_court.png)
```
The first part of the line, the one inside square brackets, represents the words that should appear in case that the image doesn't show properly. The second part is the image itself. To do in the same way you should create a folder in your repo (from Visual Studio) called `images` and save the images you wanna show there.  

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```
Similar to what I told you before, the first part is the title or what every user will see in your repo and the second part is the link to the documentation of that module. It will appear in Github in blue words as a hyperlink. 

- You forgot to create a `.gitignore` file to hide your csv file. You can do it from Visual Studio Code or PyCharm. If you have any doubt about it, don't hesitate to contact me. 

## 2. What about your code?

Your final jupyter notebook is clearly well organized and your explanations about every step that you do are good. Remember that about that last point, you can always create a *markdown* cell to give your explanations more clearly.

Great that you have imported all your libraries and your data at the beginning of your notebook! It's a very important step to do in the same way from now, forever. It helps other people who take a look to your code to check your libraries and its tools as well as your data. 

### 2.1 Exploratory analysis

Your work here is good. It's cool that you have used a lot of concepts learned in class such as `list comprehension`, `apply & lambdas`, **Pandas** methods...

Just some tips to improve: 

- The cleanliness of your dataset is not completed. You forgot to check for duplicate and you have decided to drop more than 40 columns without any explanation. That decision is crucial in the developing of your project. 

- As I said, it's important to explain why you are dropping each variable from your dataset. For example, you have removed important variables such as *BP* or *BOV*. It's fine if you remove it, but you have to give a good explanation. 

- When you use `apply` and `lambdas`, you can optimize your code defining a function or creating a list with the name of the columns and using a `for` loop to iterate by them. You will save some time doing that.

- I missed some functions or solving cleaning tasks, for example, changing the value of weight from lbs to kg. It's easy creating a function for it. In your final DataFrame, to check correlation, you still has 60 variables remaining, it would be better if you clean them a little bit more or decide to drop some of them because their significant is similar to other variables. 

### 2.2 Questions

Good work here! You have used libraries such as `matplotlib` or `seaborn` to answer your questions and show them in a prettier way, that's great!

Although the complexity of your questions is not very high, they could be useful for further approaches to your dataset. I encourage you to try to answer more difficult questions coming from these you made here. 

Finally, be careful how you show your plots, the third one is not very clear and the legend in the x-axis is difficult to see for a reader who we want to surprise with our project. 

### 2.3 Processing analysis

Once you cleaned all your data and you understood the variables you have to work with, it's time to do the processing analysis, which is the main step of a Machine Learning model. 

A few tips here to improve:

- The first step that you took was using a `box-cox transformation` to normalize the distribution of all your variables. That's not a good option since some of the variables could have a normal distribution by themselves. You can check the distribution of your variables using `distplots`. 

- You have to check for outliers in your variables and remove them. We have done that in class, so check in the notebooks that Abhi uploaded to the Github repo. 

- Remember that your R-Square value depends on which variables you choose for your model to train it and make predictions based on them. 

I have nothing else to say in your project, just remember to import all your libraries and modules at the first cell of your jupyter notebook. Good work overall, but you need to work more on your project to have a better result! You can do it!
