### ISSUE TITLE
[Nicole Richter] Project 1 FIFA Moneyball

### ISSUE THREAD

**Issue by nicolerichter1989** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#21]
https://github.com/nicolerichter1989/P1_MoneyBall_FIFA

**Comment by AnaAGG** [comment]
# ⚽️ Money Ball FIFA project Nicole ⚽️

Hi Nicole, here I am with the first project review. 

## Readme

What did I miss in your readme?
- Think that the people reading your readme have to understand every process you have gone through during your project. For that they have to understand what the data set consist of and what are the most important points. In this case, this dataset can be a bit complez because nor everyone is familiar with all the names in football. My recommendation here is to add in the readme some basic concepts so that the potential user can understand the resto of your project. 

- What it is the objective of your project??

- Regarding the libraries, put them on a list to make it more user friendly. If you add link to the official website it would be perfect. For example: 
  - pandas
  - numpy
  - matplotlib
  - ... 
  
  How can we include link in markdown?

        [pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)

        If you use this structure you create a link like the ones we create for you when we send you documentation. 

        Example 👇🏽👇🏽

    [Here](https://www.markdownguide.org/cheat-sheet/) a markdown cheat-sheet in case it help you in the future
- Regarding the use of markdown in the readme, it can be really usefull when we create a readme. I recommend that you take a look at the docu I sent you above to start getting familiar with it. 

## Repo structure

The structure is perfect, you have a readme and main jupyter and the gitignore, and the most important! No temporary files such as `vscode` or `DS_Store` have been left out of the gitignore. 

## Code syntax

- In the function `clean_char` that you created to remove specific symbols in a given columns:
    ```python
    def clean_char(x):
        if (x.startswith('€') and x.endswith('K') and (x.find('.')>=0)):
            return x.replace("€","").replace("K","").replace(".","") + "00"      
        elif (x.startswith('€') and x.endswith('K')):
            return x.replace("€","").replace("K","") + "000" 
        elif (x.startswith('€') and x.endswith('M') and (x.find('.')>=0)):
            return x.replace("€","").replace("M","").replace(".","") + "00000"      
        elif (x.startswith('€') and x.endswith('M')):
            return x.replace("€","").replace("M","") + "000000" 
        else:
            return x.replace("€","")
    ```
    Your function is perfect, but as a detail, you combine the `if` and `elif` statement alternatively. However, by convenction the normal procedure is to use `if` at the beginning, then the rest of the conditions using `elif` and finally the `else` statement. 

- When you replace the NaN values in the `club`, `a/w` and `d/w` columns, your code is perfect, but if you see you are repeating the same line of code. We should avoid this kind of repetition. What can we do??
    ```python
    # we can create a list with the names of the columns with NaN
    to_replace = ["club", "a/w",  "d/w"]

    # and then create a for loop with the code that you have
    for i in to_replace:
        data[i].fillna("UNK", inplace = True)
    # Thus, we only create one line of code. This can be a perfect option if you have many columns with NaN. 
    ```
- Suuuper this part of your code Nicole 🎉🔥

    ```python
    conditions = [
        ((age_data["age"] >= 10) & (age_data["age"] < 20)),
        ((age_data["age"] >= 20) & (age_data["age"] < 30)),
        ((age_data["age"] >= 30) & (age_data["age"] < 40)),
        ((age_data["age"] >= 40) & (age_data["age"] < 50)),
        ((age_data["age"] >= 50) & (age_data["age"] < 60))
    ]

    values = ["10-19", "20-29", "30-39", "40-49", "50-60"]

    age_data["age_group"] = np.select(conditions, values)
    ```
## TODOs

- As you said at the beginning of the jupyter, I missed some visualization. For example, in your first question, if you create multiple plots with the statistics that you have calculated, the results could be more friendly 😉 

- Create more functions to get a more cleaned code. For example
    ```python
    # when you create the displots you could create a function 
    def plot_distributions():
        for column in dfp.select_dtypes(np.number).columns:
            sns.distplot(dfp[column])
            return plt.show()
    ```
    In the future we will explain how to save these function in a `.py`file and export them to jupyter making our document much cleaner! 


All in all, good work Nicole, in this project you have reinforced the knowledge acquired so far in the bootcamp. You have explored the data, familiarised yourself with it, cleaned it and created a machine learning model with very good results. Congratulations 🔥!

![image](https://user-images.githubusercontent.com/75084991/125509106-b0533eb7-5edf-4ad9-a688-fec6598780c9.png)
