### ISSUE TITLE
P1_FIFA_CharlotteStiller

### ISSUE THREAD

**Issue by CharlotteStiller** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#3]
https://github.com/CharlotteStiller/P1_MoneyBall_FIFA.git

**Comment by Unaiat** [comment]
Hi Charlotte 🙋‍♂️ Here I send you some feedback of the first project. 

First of all, I would like to make you some recommendations about what to add in the readme:

You did an index with the workflow, which is great. Besides that, there are other elements that should be included: 

- The hypothesis (and an example of one of the visualizations)
- The R2 of the model 
- The source (the link to the kaggle database https://www.kaggle.com/ekrembayar/fifa-21-complete-player-dataset)
- The libraries that were used 

3.2. dealing with the NaN values:
2) replace null values with the most frequent value OR 2) replace null values with the mean of the column:

Here, it would be nice if you could explain the reasoning behind replacing the null values with the mean in some columns and with the mode in others. 

Regarding the first question, I would recommend you to rephrase it. I understood that you wanted to check if taller players are heavier, is it correct? If so, I would phrase it that way, as it presents a hypothesis that could be tested and visualized with a graph. 

It is great that you also used visualizations showing the distributions. Unfortunately, it is not possible to see the distribution of the weight. 

There are different alternatives for this, such as reducing the number of bars in the graph or rotating the labels. Here I send you a link where they explain how to do it:

[rotating labels in a chart](https://stackoverflow.com/questions/26540035/rotate-label-text-in-seaborn-factorplot) https://stackoverflow.com/questions/26540035/rotate-label-text-in-seaborn-factorplot

After the heatmap when dropping the columns with a correlation > 0.9you have an error, but it is just because you included the word `drop` as a column. 

Just FYI, there is a function that Abhi created, which you can use to remove the outliers:

```Python
def remove_outliers(df_model, threshold=1.5, in_columns=df_model.select_dtypes(np.number).columns, skip_columns=[]):
    for column in in_columns:
        if column not in skip_columns:
            upper = np.percentile(df_model[column],75)
            lower = np.percentile(df_model[column],25)
            iqr = upper - lower
            upper_limit = upper + (threshold * iqr)
            lower_limit = lower - (threshold * iqr)
            df_model = df_model[(df_model[column]>lower_limit) & (df_model[column]<upper_limit)]
    return df_model
```

All in all, the project is very good. You followed all the steps, have a great structure and got a very good result.

Your question were interesting and you answer them clearly using visualizations. This is very important as a data analyst, so it is very good that you are already doing it 😀

Please, let us know if you have any question. 

Keep up the good work!!! 🚀
