### ISSUE TITLE
Project Tom Dubun

### ISSUE THREAD

**Issue by TomDubun** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#5]
https://github.com/TomDubun/Project_FIFA_MoneyBall.git

**Comment by AnaAGG** [comment]
# ⚽️ Money Ball FIFA project ⚽️

Hi Tom, here I am with the first project review. 

## Readme

- Suuper that you start the readme with the objective of the project 🚀

- In the `DATA CLEANING` section you explain the cleaning process that you apply for each selected variable, which it is perfect! Just as a detail, this datset could be a bit complex because it have a lot of columns with a lot of information about concepts that some people may find confusing or simply not know. One thing that you could do is add a little description about each of the concepts. 

What did I miss in your readme?

- Variable description 

- You can also include a link to the kaggle website wehere you downloaded the data from.
- One importatn thing I missed in your readme are the libraries that you have used in the project. You can put them on a list and if you add link to the official website it would be perfect. For example: 
  - pandas
  - numpy
  - matplotlib
  - ...
  
        [pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)

        If you use this structure you create a link like the ones we create for you when we send you documentation. 

        Example 👇🏽👇🏽

    [Here](https://www.markdownguide.org/cheat-sheet/) a markdown cheat-sheet in case it help you in the future
 

Overall, really good job in the readme, you have included all the needed information, the data cleaning section is more than perfect. Work on the small changes I proposed and you will have a perfect job 🚀🔥💪

## Repo structure

Nothing to tell you on this part Tom, you have a very well organised repo. You have created different folders where you keep the data and image, and the most important! No temporary files such as `vscode` or `DS_Store` have been left out of the gitignore. 
 

## Code syntax

- Super Tom you have used functions to avoid repeated the same code many times 👏🏽. To be picky, when you apply the `currency_cleaner` you repeated the same line of code three times. Now, imagine that you have 20 columns to cleaning... it could be a bit painful... So, you can also atomize this part of you code using a `for` loop. 

    ```python
    #create a list with the target columns 
    lst_columns = ["wage", "value", "release_clause"]

    # iterate over the list and "call" your function

    for i in lst_columns:
        df[i] = df[i].apply(currency_cleaner)
    # with this you have changed all the columns with only three lines of code. 

    # 🔴 You can do the same with the next step where you convert these columns to float.  
    ```
- In the `weight_converter` function, to be picky again (but you have really good code in this project and I give you a correction with details)

    ```python
    def weight_converter(x):
        if 'lbs' in str(x):
            x = str(x).replace('lbs',"") 
            x = float(x) * 0.4535 # you can move this line of code and put it directly in the return 
        return float(x)
    # the thing that try to do is reduce the function. So the first question here is: Why do you use float twice??
    # In addition, you could put all the code in one line 
    def weight_converter(x):
            if 'lbs' in str(x):
               return float(str(x).replace('lbs',"")) * 0.4535
    ```
- When you remove ★ from some columns, you can also create a function or use a `for` loop to avoid repeating code. 
    ```python
    lst_convert = ["w/f", "sm", "ir"]
    for column in lst_convert:
        df[column] = df[columns].str.replace('★', '')
        df[column] = df[column].astype(float) 
    ```
- In the standarization of features you normalize the numerical columns, but when you fit the model you use the data non-normalized, why?? if you will not use this transformed data, I recomended you that remove this code from the jupyter
  
- Overall you have done a very good job Tom. especially on the dataframe cleaning part, congratulations 🎉!

## TODOs

- In the jupyter I have missed a little more order in terms of headings and comments along the jupyter, I recommend you to work a little more on this part in future works. I leave [here](https://www.earthdatascience.org/courses/intro-to-earth-data-science/file-formats/use-text-files/format-text-with-markdown-jupyter-notebook/) a link that can be useful to work with markdown in jupyter.
  
- Some visualization for example with the tables that you get with the most valued players. Your tables and results show clearly your hypothesis, but visualization could be more friendly for a person (or customer) who is not familiar with python. 
Remember, you have a lot of libraries in python that you could use with this objetive, my favorite... [plotly](https://plotly.com/python/plotly-express/)

All in all Tom, you have done an amazing job on your first project. In this project you have reinforced the knowledge acquired so far in the bootcamp. You have explored the data, familiarised yourself with it, cleaned it and created a machine learning model with very good results, and you have added more data, amazing🚀🚀🔥🔥!!!!

![image](https://user-images.githubusercontent.com/75084991/126040706-681040a7-9b76-4091-9bd5-31c5ba483c89.png)
