### ISSUE TITLE
Project_FIFA_MoneyBall_Kathi

### ISSUE THREAD

**Issue by katharina-beriault** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#6]
https://github.com/katharina-beriault/Project_FIFA_MoneyBall_Kathi

**Comment by Unaiat** [comment]
Hi Katharina 🙋‍♂️ Here I send you some feedback of the first project. 

First of all, I want to congratulate you because you did an excellent project. It is very well structured and is easy to follow. 

There is not much I can tell you to improve it. 

Your readme is very good, you explain what you are going to do clearly. This helps to understand the code much better. You can also add images and gifs if you like it, with the following code:

```python
<img width=1000 src="path where the image is stored in your computer">
```

please also import all the libraries at the beginning 😀. You basically made it, except the `from scipy.special import inv_boxcox` and `import math` at the end of the notebook. Again, this is a convention and not a mistake. 

All in all, the project is very good. You followed all the steps, have a great structure and got a very good result.

Your question were interesting and you answer them clearly using visualizations. This is very important as a data analyst, so it is very good that you are already doing it 😀

Please, let us know if you have any question. 

Keep up the good work!!! 🚀
