### ISSUE TITLE
Projet FIFA - Izel Yekrek 

### ISSUE THREAD

**Issue by izelyekrek** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#7]
https://github.com/izelyekrek/P1_MoneyBall_Fifa.git

**Comment by AnaAGG** [comment]
# ⚽️ Money Ball FIFA project ⚽️!
Hi Izel, here I am with the first project review. 

## Readme

- Suuper Izel, you have defined an objective in the readme, this is essential in our projects 💪. 

- Really good documented the workflow of your project in the point 3 🔝. 

What did I miss in your readme?

- This datset was characterised by the fact that it was quite complex. You explained why you were left with a subset of variables, but to be picky it would have been perfect if you has explained a bit what each of the variables you included meant. 

- One importatn thing I missed in your readme are the libraries that you have used in the project. You can put them on a list and if you add link to the official website it would be perfect. For example: 
  - pandas
  - numpy
  - matplotlib
  - ... 
  
  How can we include link in markdown?

        [pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)

        If you use this structure you create a link like the ones we create for you when we send you documentation. 

        Example 👇🏽👇🏽

    [Here](https://www.markdownguide.org/cheat-sheet/) a markdown cheat-sheet in case it help you in the future

Overall, good job in the readme, I have little to say to you, to be honest, I found it very complete. For the next project work on these details and ot will perfect🚀! 

## Repo structure

Overall, the structure of the repo is perfect, you have all the required files and the most important! No temporary files such as `vscode` or `DS_Store` have been left out of the gitignore. 

I only have a detail here:  

- You have two images in your repo. The best way ti proceed in these cases is to create a folder insede the repo that you can call "images" where you can save all the images you want. This way evverything will be much more tidy and you will avoid having loose files lying around 😉! In the same way you can also create a folder to the data 💪

## Code syntax

- In the readme you wrote this comment: `I decided to create directly a new dataframe with the columns that I need for my 3 questions and for the linear regression model.`. Suuuper Izel! 
One of the important points in this project was to know how to manage very well the large number of varaibles that we had and to keep only those that were of interest to us. 

- Wow!! You have not only worked with python but you have added value to the project by working with SQL as well. 

- In the jupyter, you have some lines of code that you have repeated many times to cleaning some columns, for example: 
    ```python
    # you have used this method in two different columns, "value" and "wage" 
    fifa['value'] = fifa['value'].replace({'K': '*1e3', 'M': '*1e6', '€': ''}, regex=True).map(pd.eval).astype(int)
    ```
    To avoid having duplicate code we can create functions, for example: 
    ```python
    def cleaning (df, col):
        return df[col].replace({'K': '*1e3', 'M': '*1e6', '€': ''}, regex=True).map(pd.eval).astype(int)
    ```
    Moreover, in this function you can have all the cleaning processes you want and in one go, by calling a function you clean the whole dataset.
- Only as a detail, in python there is a convention by which the `import` go to the beginning of the jupyter. 

- In the section 4 **Visualization**, super that you create this section, but... you haven't made any plot!! What happended here? your tables and results show clearly your hypothesis, but visualizatio could be more friendly for a person (or customer) who is not familiar with python. 
Remember, you have a lot of ibraries in python that you could use with this objetive, my favorite... [plotly](https://plotly.com/python/plotly-express/)

- In the same way that in the cleaning process, when you remove the outliers you have the same code repeated many times. Remmember 🤓, functions are our best friends!!!

- Why only numerical columns?? Probably, if you include the categorical ones, the R2 of your model improvess
- 
## TODOs

- I noticed that you have used the spearman correlation in the model. It would be great if you could explain why you have chosen this correlation and not the pearson, so that it is clear that you understand the process you are doing!

- Overall, you jupyter is good documented, but i missed more information about some decisions you take along the preocess or more explanations about your results. 

- I encourage you to use the functions in future projects, they are super useful and will make our jupters cleaner. 

All in all, good work Izel, in this project you have reinforced the knowledge acquired so far in the bootcamp. You have explored the data, familiarised yourself with it, cleaned it and created a machine learning model with very good results. Congratulations 🔥!

![image](https://user-images.githubusercontent.com/75084991/125971634-175cf0be-ee53-4372-9db1-3e7b661e6e7b.png)
