### ISSUE TITLE
[Project_FIFA_MoneyBall] Claudia Carloni

### ISSUE THREAD

**Issue by ClauCarloni** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#8]
I got some problems with my moving and I must fix it today, so I'll be not able to follow the presentation.
In order to provide our 'competition' with more data here is my preliminar work:
https://github.com/ClauCarloni/P1_FIFA_MoneyBall.git

**Comment by Unaiat** [comment]
Hi Caudia 🙋‍♂️ Here I send you some feedback of the first project. 

First of all, I would like to make you some recommendations about what to add in the readme. The first point is correct, as it shows your questions/hypothesis. 

But the next ones, you actually have to add the actual info.

Also, please insert line breaks between so everything does not end as a single paragraph. 

In the main notebook you have the following line where you import the libraries: `LIFE_UNIVERSE_AND_EVERYTHING = 42`. Then, you use it to define the `random_state` when splitting the data. I would recommend you to delete this variable, and put the value directly instead of using that line. 

When reading the csv, you do not need to put the whole path to the file, just the relative path is enough. 

The relative path starts in the current working directory, that is, the directory where the notebook is saved. The relative path would be the following:

```python
data = pd.read_csv('./Data/fifa21_male2.csv')
```
Please note that the ipynb file and the folder where the csv file is need to be in the same level (inside the same folder). 

This is important, as otherwise if someone else downloads your folder the code will not work, and they will need to change the path. 

You used the mode to fill the NaN values of some of the rows, which is a valid way of doing so. It would be nice if you would include a comment explaining why you took that decision. 

In the readme you presented interesting questions, now you need to work on the questions and prove or reject your hypothesis using graphs. 

We are aware that you were moving and had some issues, which didn't allow you to work on the project as much as you wanted. These comments are just for you to have a guide to improve the project and finish it, so you can have it as a presentation of your work during the bootcamp. 

Please, let us know if you have any question. 

Keep up the good work!!! 🚀
